# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push image to container registry
      inputs:
        command: buildAndPush
        repository: images
        dockerfile: '$(Build.SourcesDirectory)/web/dockerfile'
        containerRegistry: webdockerregistry
        tags: latest

- stage: DeployDev
  displayName: Deploy to Development stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy    
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'develop-v1'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy web app
            inputs:
              azureSubscription: 'Evaluación gratuita (f23f26a0-2935-4461-ad9f-394814164bd7)'
              appName: 'webgaliciadev'
              containers: 'azregistry2.azurecr.io/images:latest'

- stage: DeployProd
  displayName: Deploy to Production stage
  dependsOn: DeployDev
  jobs:
  - deployment: Deploy
    displayName: Deploy    
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'prod-v1'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy web app
            inputs:
              azureSubscription: 'Evaluación gratuita (f23f26a0-2935-4461-ad9f-394814164bd7)'
              appName: 'demogalicia'
              containers: 'azregistry2.azurecr.io/images:latest'